### ISSUE TITLE
Flow request

### ISSUE THREAD

**Issue by lappat** [thingzi/thingzi-logic-climate#1]
Hi,

this is not a issue, but i'm starting with Node Red and wwould like to  know if you can share your setup, i have 1 HVAC GAZ Zwave at home, with 3 zwave thermostat for electric heating.

Can you share your FLOW?

Thanks

**Comment by bryzix** [comment]
i have a few unreleased custom nodes so its not so easy to share but i can give you an overview.  Note that my house is heat only as im in the UK and we generally have radiators but most of what i say works for HVAC too.  

I have a 3 dedicated heating zones, 2 underfloor and 1 covering the rest of the house.  This means that effectively i have 3 on/off switches for heating.

For each room i use one instance of the climate node to manage its temperature.  In each room i have a thermostat which i feed into the climate note to help it decide if to heat or not.  The output of each climate node is used to control the room specific heating device i.e. underfloor in 2 rooms and the radiators in the other rooms as i have controllable radiator valves in each room.

To manage the fact that the majority of rooms share a single heating zone i use a node to test all radiators to see if any are "calling for heat" and if one is then that heating zone is "on".

I also use the thingzi-logic-timers schedule node to handle when to turn everything on/off.  Some pics (ive simplified the main zone as there are 8 rooms i cover)....

<img width="887" alt="image" src="https://user-images.githubusercontent.com/46371227/154811918-7cbc3583-2053-436b-931b-967220619662.png">

<img width="503" alt="image" src="https://user-images.githubusercontent.com/46371227/154811947-519eb775-e4e6-480b-b46d-680b38ed1952.png">

Finally i also advertise each control to homeassistant via mqtt which lets me do this...

<img width="503" alt="image" src="https://user-images.githubusercontent.com/46371227/154812013-b4f17836-e45b-414d-ac0f-487cf8493561.png">

**Comment by lappat** [comment]
Thanks for your quick reply, i will look at it!
