### ISSUE TITLE
configuration

### ISSUE THREAD

**Issue by merlino1975** [thingzi/thingzi-logic-climate#11]
I'm trying to configure the node. but I can't figure out how to make it work properly.
I'll first introduce you to what I would like to obtain, then tell me if your node can be configured to obtain it
I would like the pellet stove to turn on in the morning if the temperature in the house drops below x degrees, to turn on and be set to a specific power. I would like that once the temperature reaches a temperature of y the stove goes into saving mode, i.e. it stays on but has minimal power. if the temperature rises further, when temperature z is reached it switches off. and restarts if the temperature drops below the determined value w
If I wasn't clear please let me know. Thanks for the help

**Comment by bryzix** [comment]
So this may be possible with a bit more effort... how i would approach it...

- Default setpoint is set to Z (i.e. the target temp)
- Add nodes to monitor the heating mode and apply your rules based on current temp e.g.
  - When the temp is below Z, heating will be "ON" and you can check the temperature to decide the power mode based on your rules
- While this isnt exactly what you describe, it would be able to start on the saving mode when temp was higher, if that was a valid use case
  - However, if you wanted to orchestrate it exactly as you describe you could manage your own state i guess
  - Also note that the "tolerance" setting creates a dead zone around Z which you can also use

Simpler example without function nodes...

<img width="1080" alt="image" src="https://github.com/user-attachments/assets/edb48bad-38cc-447a-bd93-68b6fd38bdef">

Another approach with a function node (gives much more control)...

<img width="796" alt="image" src="https://github.com/user-attachments/assets/5b0398c6-87af-4058-b489-3cea8036ce59">

In this one you enable debug mode, which gives a full state on every change and you can apply your own logic on top, assuming you are comfortable with a bit of coding!

**Comment by merlino1975** [comment]
Thanks for the suggestions:
However, I want to ask you to show me, if possible, how the fields of the house climate node are set, I have difficulty setting those values. Set up and also understand the logic behind it. The meaning of the various fields.

**Comment by bryzix** [comment]
If you hover over the text on each field it gives you a description of what it does.  If you have more specific questions I'm happy to help.

**Comment by merlino1975** [comment]
forgive me, but I often use Samsung dex (I connect my smartphone to the computer), and on this platform when hovering the mouse over the fields the suggestions do not appear

**Comment by bryzix** [comment]
Property descriptions...

### Configuration

**Keep Alive**
Some receivers will need regular keep alive messages to prevent a safety cut off.  A regular update also ensures devices are kept in sync if a message is lost. 0 means no keep alive.

**Min Cycle**
Minimum time for any heating/cooling cycle. Once the cycle begins it will not change for this duration with subsequent requests queued.  This protects equipment such as boilers, which can be damaged by quick changes.  The * symbol will be shown on the node status when a change is pending that occured too quickly.

**Boost For**
Duration of climate boost.  This will override any other input settings for the duration of the boost and is designed to overlap scheduling events if needed.

**Std Preset**
Identifier to use for default preset, e.g. none, standard or default.  Allows more clarity for specific use cases. Default is 'none'

### Set Point

**Degrees**
Measurement scale to use for temperature

**Default**
Default set point of the climate controller.  Can be overridden by 'setpoint' input

**Tolerance**
Heating tolerance around the set point. Heating or cooling will be disabled within this range to avoid overshooting the set point.

**Min Temp**
Minimum set point temperature

**Max Temp**
Maximum set point temperature

**Temp valid**
Duration for which the last temperature is valid.  Protects against cases where a thermostat fails with a lower reading and heating is stuck on.  If the time expires a safety cut off will remain active until a new temperature reading is received.

**Swap Delay**
Minimum time to wait before switching from heating to cooling or vice versa.  Without this heating & cooling may compete against each other
