### ISSUE TITLE
cant figure out

### ISSUE THREAD

**Issue by mjay9876** [thingzi/thingzi-logic-climate#2]
hallo 

can you make a short introduktoin on how you have to do the input so it will work i cant figure it out it just say waiting on tempature :(

i have add a picture of what i have tryed im new in this so i hope its okay im asking

best regards mikkel
![123](https://user-images.githubusercontent.com/77259963/162529548-c147297c-71d0-451d-86dd-32dea69a3389.png)

**Comment by bryzix** [comment]
I'll see if I can improve that.  In the mean time if you set the output topic of your temperature node to "temp" and link it to the climate node that should work.  

There are some docs on the node itself about inputs & outputs.  Plus more info on node properties if you hover over names.

**Comment by mjay9876** [comment]
Okay like a json string or ?

And how do I do with the setpoint ?

So it is "temp , 23" or ?

Hope it's okay I'm asking im totalt new :)

Mikkel

lør. 9. apr. 2022 07.58 skrev thingzi ***@***.***>:

**Comment by bryzix** [comment]
Looks like you are using home assistant nodes.  I think you can set the topic output on that.  If not you can use a change node to do it.  

For set point you can either do the same using the "set point" topic or advertise the climate node direct to hass via MQTT which makes it appear as a thermostat (if you have MQTT set up with hass that is.

As I said before these inputs and outputs are listed in the node documentation.  Click on the climate node and select the documentation tab on the right.

**Comment by bryzix** [comment]
By default most nodes use the "payload" topic.  It's just the topic name that need to change, no json required.

**Comment by mjay9876** [comment]
okay i will try that but i have to use mqtt for home assistant to control
it ?

i have read everything but its not that easy to understand :)

Den lør. 9. apr. 2022 kl. 08.20 skrev thingzi ***@***.***>:

**Comment by mjay9876** [comment]
Can you send me a screen dump of the mqqt you have to send or the change
note ? I have tried to write "temp23" and it still will not :(

If you don't want it's okay ?

lør. 9. apr. 2022 08.27 skrev Mikkel Jensen ***@***.***>:

**Comment by bryzix** [comment]
Might be worth reading up on how topics work in node red as they are different from the data you send. 

The data you send between each node is on a topic (which has a name) along with the data.  By default node red messages are sent using the "payload" topic.  You can change this though.

The message for temp needs to have the topic "temp" & the data is the numerical value.  Have a look at the hass event node as it lets you change the topic in its settings.

I'm travelling at the moment but when I get some time over the next couple of days I'll share an example for you.

**Comment by mjay9876** [comment]
Thank you very much have a nice vacation

lør. 9. apr. 2022 11.53 skrev thingzi ***@***.***>:

**Comment by bryzix** [comment]
This is how I set mine up.  Doesn't show how topics work but gives an idea what is possible

See my reply in this thread 
https://github.com/thingzi/thingzi-logic-climate/issues/1

**Comment by mjay9876** [comment]
Thanks I will look on it tomorrow :)

lør. 9. apr. 2022 12.06 skrev thingzi ***@***.***>:

**Comment by mjay9876** [comment]
i got it working thanks for your help

Den lør. 9. apr. 2022 kl. 12.06 skrev thingzi ***@***.***>:
