### ISSUE TITLE
Keep Alive not sending output message

### ISSUE THREAD

**Issue by lucibuz** [thingzi/thingzi-logic-climate#4]
Hello,
thanks for developing the climate node, all works well, my only issue is with the keep alive feature.
My understanding is that keep alive resend the state of the heating/cooling output at the time interval set, but never does it no mater the set time.
Is something that I do wrong or this feature has a different role?

thanks in advance
Lucian

**Comment by bryzix** [comment]
That's the idea.  As you have mentioned it I will double check my testing script to see if this working as it should.

**Comment by lucibuz** [comment]
thank you,
much appreciated

**Comment by bryzix** [comment]
Yeah, looks like a bug.  Every time it receives a temp update it extends the keep alive time and an update is not sent if the state output is unchanged.  As this is quite normal behaviour its likely the keep alive will not get triggered at all.  Ive created a fix and will push it shortly once ive completed testing.

**Comment by bryzix** [comment]
Is fixed now in 0.5.4.  Let me know when you can test and i will resolve this issue.

**Comment by lucibuz** [comment]
Works perfect now.
thanks for your time and effort.

**Comment by lucibuz** [comment]
Hello again,
maybe you can help me with the Temp Valid feature, when missing the temp input message the node enters the "waiting for temp" state but doesn't send the heating/cooling OFF message. Not sure if this is intentional but definitely will help if lousing input temp value occur when in heating/cooling cycle.
Thanks.

**Comment by lucibuz** [comment]
I also have a suggestion :-) , a pull request, if possible will be nice to have a counter for the ON state / 24 hours (heating/cooling), and an output message. This helps measuring the heating/cooling consumption / day (now I'm doing it using additional nodes).
Thanks.

**Comment by bryzix** [comment]
I think sending off when losing temp updates is a good safety cut off feature to have.  I may take a look at this later in the week.

Not too sure about having a counter though.  Feels like that maybe a step too far for the node and much better to use a different node for this.

**Comment by bryzix** [comment]
closing this as original bug is fixed.  watch out for 0.6.0 where i have reworked how i handle updates so that loss of temperature will trigger an off command rather than do nothing
