### ISSUE TITLE
Loss of temperature issues

### ISSUE THREAD

**Issue by tek79** [thingzi/thingzi-logic-climate#5]
In testing release 6.0.2, node outputs aren't reliably sending an 'OFF' message on loss of temperature, and the node status dot sometimes stays yellow while displaying 'waiting for temp...' In this case, mqtt action is also not set to idle. Possibly related, I am also seeing erroneous changed=true and pending=true messages coming from the debug output in the middle of a cycle, with no changes made.

**Comment by bryzix** [comment]
i will take another look at this.  ive also tried to improve the keep alive messages which were broken which currently trigger a "change" event so i may tweak that so it doesnt do it on keep alive.

**Comment by bryzix** [comment]
can you let me know the node settings you used for testing this please?

**Comment by bryzix** [comment]
Had a look and it may be your particular settings are triggering the cycle logic which stops it changing too fast.  This was triggered by keep alives in that version which isnt right so ive split it out again so keep alives no longer trigger that change logic.  This should stop the noise you are seeing at least and *may* explain not sending the event if its waiting to cycle.  if you can test 0.6.3 again and let me know what you find.  Note 6.0.2 was a typo and should have been 0.6.2 :)

**Comment by tek79** [comment]
Settings are as follows for my testing: 
Type: Heating & Cooling
Debug Out: true
Keep Alive: 1 minute
Min Cycle: 90 seconds
Temp Valid: 1 minute

Inputs:
temp="72"
setpoint="72.5"
mode="heat"

temp is sent on 10 second intervals. I was seeing the erroneous 'change' happen after about a minute, and as you stated, seemed to correspond with the sending of the first keep alive. My test was simply to interrupt and re-establish the temp input randomly and see how it responded. I had made an attempt at this with my forked version, and it is working, but then you posted your release a few hours later with the same feature. I should have just asked. :) I will give the new release a try this afternoon.

**Comment by bryzix** [comment]
Ok, it's likely the fact the cycle time was longer than the keep alive time.  As it treated keep alives as a change in 0.6.2 this would cause issues.  I will try this combo out too on 0.6.3.

**Comment by tek79** [comment]
It seems to be working as intended in 0.6.3.
