### ISSUE TITLE
Boost config

### ISSUE THREAD

**Issue by germaguire** [thingzi/thingzi-logic-climate#6]
Hi, I am trying to figure out how to use the boost function but I havent had any success.

I have tried passing: 
msg.mode with payload of boost
msg.boost with payload of ON
msg.boost with payload of true
msg.boost with payload of 30 (time)

Could you provide a sample flow with the boost features for the climate please?

Thanks,
Ger.

**Comment by bryzix** [comment]
boost topic should work fine with ON/true values.  Note that you cannot set the boost time via messages though, only config.  Also take note of the cycle time.  

<img width="375" alt="image" src="https://user-images.githubusercontent.com/46371227/222858195-2c95078a-0528-4bd4-ad61-af9e0e9ed84d.png">

This is the minimum time between any change of state to protect heating units from fast switching, it may be your change worked and the switch was pending. 

Here is an example of boost usage (remember to set the temp 1st too)...

[{"id":"8d0f3abf9e74f7d5","type":"inject","z":"46f4e38d80544a20","name":"Boost ON","props":[{"p":"boost","v":"ON","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","x":310,"y":730,"wires":[["103137ad17dcf168"]]},{"id":"5d1925de60acfab7","type":"inject","z":"46f4e38d80544a20","name":"Boost OFF","props":[{"p":"boost","v":"OFF","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","x":310,"y":760,"wires":[["103137ad17dcf168"]]},{"id":"103137ad17dcf168","type":"thingzi-climate","z":"46f4e38d80544a20","name":"Heating","climateType":"heat","sendStatus":true,"keepAlive":"1","cycleDelay":"10","boostDuration":"2","degrees":"C","defaultSetPoint":20,"tolerance":0.2,"minTemp":5,"maxTemp":25,"tempValid":"3","swapDelay":60,"onPayloadType":"bool","onPayload":"true","offPayloadType":"bool","offPayload":"false","advertise":true,"broker":"ac5f6429fdbd3eb1","topic":"climate","outputs":3,"x":510,"y":740,"wires":[["f3c22be8d2abf274"],[],[]]},{"id":"f3c22be8d2abf274","type":"debug","z":"46f4e38d80544a20","name":"Debug","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","targetType":"msg","statusVal":"","statusType":"auto","x":680,"y":740,"wires":[]},{"id":"99dd24c091f0991f","type":"inject","z":"46f4e38d80544a20","name":"Temp 18","props":[{"p":"temp","v":"18","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","x":310,"y":650,"wires":[["103137ad17dcf168"]]},{"id":"cba4e1de2d52bf0f","type":"inject","z":"46f4e38d80544a20","name":"Setpoint 20","props":[{"p":"setpoint","v":"20","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","x":300,"y":810,"wires":[["103137ad17dcf168"]]},{"id":"6f1737436c0a2353","type":"inject","z":"46f4e38d80544a20","name":"Setpoint 22","props":[{"p":"setpoint","v":"22","vt":"num"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","x":300,"y":840,"wires":[["103137ad17dcf168"]]},{"id":"c9a60db88bf61dc7","type":"inject","z":"46f4e38d80544a20","name":"Temp 21","props":[{"p":"temp","v":"21","vt":"num"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","x":310,"y":680,"wires":[["103137ad17dcf168"]]},{"id":"ac5f6429fdbd3eb1","type":"mqtt-broker","name":"","broker":"host.docker.internal","port":"1883","clientid":"","autoConnect":true,"usetls":false,"protocolVersion":"4","keepalive":"60","cleansession":true,"birthTopic":"","birthQos":"0","birthPayload":"","birthMsg":{},"closeTopic":"","closeQos":"0","closePayload":"","closeMsg":{},"willTopic":"","willQos":"0","willPayload":"","willMsg":{},"sessionExpiry":""}]

**Comment by germaguire** [comment]
Thanks for the example and the quick response, thingzi looks really good and I am about to start switching my own custom flows across to test.

**Comment by bryzix** [comment]
Cool, let me know if you have any feedback.
