### ISSUE TITLE
Settings temperature

### ISSUE THREAD

**Issue by WalterPepeka** [thingzi/thingzi-logic-climate#8]
Hi,
I like to use your node with PT100 probes (0.05°C accuracy)
Is it possible to improve the precision of settings temperatures (default, Min temp, Max temp), eg 18.4 instead 18 or 19?

**Comment by bryzix** [comment]
Those settings will accept typing in values such as 18.4 as things stand.  The form validation may complain but it should work as there is no logic to round anything outside of the editor.  The same is true of setpoint as you can pass this via the setpoint topic into the node at any accuracy.  The rounding is just in the front end for convenience.  

I will take a look if this can be configured as it would be a nicer user experience but you should be able to use the current version just fine.  Let me know if you are blocked though.

**Comment by WalterPepeka** [comment]
Thank you for your additional information.
I'm looking to implement this node for my brewery and the usage (along with the temperature display with decimal) is an important parameter to me.
So I'm going to test the node as is for now

**Comment by bryzix** [comment]
Sounds interesting, Bear in mind the max/min temps are there to limit the set point (target temp).  One main use case is proving the set point range for systems such as home assistant, so other than this they do not factor into calculations.  As long as the set point is within this range that's fine.

When in heat mode, the node will try to reach the set point (via on/off heat message) and cut off at (set point - threshold).  Current temp is passed into the node via a message with topic "temp". It works well for my home heating anyway 😄

This is a different use case than I've previously considered so let me know how you get on or have suggestions for improvements.
