### ISSUE TITLE
Setting tolerance

### ISSUE THREAD

**Issue by Kaiteki666** [thingzi/thingzi-logic-climate#9]
Hello,
is it possible to change the "tolerance" parameter dynamically while the flow is running, because at the moment I can only change this parameter during setup? If there is no such opportunity now, can I expect such an opportunity in the future?

Thank you for your work!

**Comment by bryzix** [comment]
Hi, sorry for not replying for so long.  I think this is a good idea and easy to add so ive released an update v1.0.4 that contains exactly this.  If you pass a topic of "tolerance" it will set it at run time and will reset to the default value after any deploy.  The debug status output now also contains tolerance if you need to check what this is.
